language: python
sudo: false

notifications:
  - email: false

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: osx
      osx_image: xcode9
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=3.5

before_install:
  - download () { curl $1 > install.sh; }
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      download https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
    else
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        download https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
      else
        download https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      fi
    fi
  - /usr/bin/bash install.sh -bt

install:
  - conda create env -n data-visualization-tutorial -f conda-env.txt -y

script:
  - conda list --explicit
  - jupyter notebook --no-browser
