language: python
sudo: false

notifications:
  - email: false

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: osx
      osx_image: xcode9
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=3.5

before_install:
  - source ci/travis/before_install.sh
  - section_begin install_conda
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      download https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
    else
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        download https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh;
      else
        download https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
      fi
    fi
  - bash install.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - section_end install_conda

install:
  - conda env create -f environment.yml
  - source activate dv-tut
  - conda install -y pytest

script: ci/travis/script.sh
